- name: Installing niginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Removing content from the folder
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Downloading the frontend content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: copying and extracting on remote system
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copying roboshop config file to frontend
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart niginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

